// Mocks generated by Mockito 5.4.6 from annotations
// in weather_todo/test/unit/todo_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_todo/data/repository/todo/todo_repository.dart' as _i2;
import 'package:weather_todo/domain/models/todo.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Todo>> get todos =>
      (super.noSuchMethod(
            Invocation.getter(#todos),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  _i3.Future<List<_i4.Todo>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: _i3.Future<List<_i4.Todo>>.value(<_i4.Todo>[]),
          )
          as _i3.Future<List<_i4.Todo>>);

  @override
  void addTodo(_i4.Todo? todo) => super.noSuchMethod(
    Invocation.method(#addTodo, [todo]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTodo(_i4.Todo? newTodo) => super.noSuchMethod(
    Invocation.method(#updateTodo, [newTodo]),
    returnValueForMissingStub: null,
  );

  @override
  void removeTodo(_i4.Todo? todo) => super.noSuchMethod(
    Invocation.method(#removeTodo, [todo]),
    returnValueForMissingStub: null,
  );
}
